### ISSUE TITLE
index.html is absent

### ISSUE THREAD

**Issue by DenisPushkarev** [membraneframework/membrane-demo#9]
Trying out example application and getting an error:
Request: GET /room1
** (exit) an exception was raised:
    ** (File.Error) could not read file stats "priv/static/html/index.html": no such file or directory
        (elixir) lib/file.ex:403: File.stat!/2
        (plug_cowboy) lib/plug/cowboy/conn.ex:41: Plug.Cowboy.Conn.send_file/6
        (plug) lib/plug/conn.ex:458: Plug.Conn.send_file/5
        (example_simple) lib/plug/router.ex:259: Example.Simple.Router.dispatch/2
        (example_simple) lib/simple/router.ex:1: Example.Simple.Router.plug_builder_call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
        (cowboy) /Users/den/proj/membrane/membrane-demo/webrtc/simple/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/den/proj/membrane/membrane-demo/webrtc/simple/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3

seems like static content was not included in repo

**Comment by DominikWolek** [comment]
Closed in 6f22c1542af1b2b891a17f8d0748241545c2aff8
